---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-web-app
  template:
    metadata:
      labels:
        app: dummy-web-app
    spec:
      containers:
      - name: webserver-simple
        image: docker.io/kostiscodefresh/preview-env-source-code:latest
        ports:
        - containerPort: 8080
