apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-kustomize-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kostis-codefresh/preview-env-manifests.git
    targetRevision: HEAD
    path: kustomize
    kustomize:
      images:
        - docker.io/kostiscodefresh/my-preview-app:aff033f
      patches:
        - target:
            kind: Deployment
            name: simple-deployment
          patch: |-
            - op: replace
              path: /spec/template/spec/containers/0/env/0
              value: 
                name: GIT_BRANCH
                value: 'replaced_branch' 
            - op: replace
              path: /spec/template/spec/containers/0/env/1
              value: 
                name: GIT_HASH
                value: 'replaced_hash'     
  destination:
    server: https://kubernetes.default.svc
    namespace: dummy-kustomize
  syncPolicy:
    automated:
      prune: true  
    syncOptions:
    - CreateNamespace=true    