apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kostis-codefresh/preview-env-manifests.git
    targetRevision: HEAD
    path: k8s 
  destination:
    server: https://kubernetes.default.svc
    namespace: dummy
  syncPolicy:
    automated:
      prune: true  
    syncOptions:
    - CreateNamespace=true    