apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapps
  namespace: argocd  
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - pullRequest:
      github:
        owner: kostis-codefresh
        repo: preview-env-source-code
      requeueAfterSeconds: 180
  template:
    metadata:
      name: 'myapp-{{.branch}}'
    spec:
      source:
        repoURL: 'https://github.com/kostis-codefresh/preview-env-manifests.git'
        targetRevision: HEAD
        path: kustomize-preview-app/ 
        kustomize:
          images:
            - 'docker.io/kostiscodefresh/my-preview-app:{{.head_short_sha_7}}'
      project: "default"
      destination:
        server: https://kubernetes.default.svc
        namespace: 'preview-{{.branch_slug}}'
      syncPolicy:
        automated:
          prune: true  
        syncOptions:
        - CreateNamespace=true 